name = "phrasebook"
defaultTargets = ["Phrasebook", "phrasebook"]

[leanOptions]
linter.unusedVariables = false # Disabled because it gives false positives when the variable is used in inline Verso code blocks.

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.30.0-rc2"

[[require]]
name = "add-combi"
git = "https://github.com/leanprover-community/add-combi"
rev = "master"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"

[[lean_lib]]
name = "Phrasebook"

[[lean_exe]]
name = "phrasebook"
root = "Main"
