/-
Copyright (c) 2026 Oliver Nash. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Oliver Nash
-/

import VersoManual
import Phrasebook.Meta.Lean
import Mathlib

-- This gets access to most of the manual genre (which is also useful for textbooks)
open Verso.Genre Manual

-- This gets access to Lean code that's in code blocks, elaborated in the same process and
-- environment as Verso
-- Write a code block with ```savedLean ... ``` to save it to an external file.
open Verso.Genre.Manual.InlineLean


open Phrasebook

set_option pp.rawOnError true

#doc (Manual) "Topological vector spaces" =>

We describe Mathlib's theory of topological vector spaces in the sections below. The theory
supports a broad class of coefficients, including $`ℝ`, $`ℂ`, $`ℚ_p` (the p-adics).

# General topological vector spaces

```lean -show
section Temporary
```

The following code adds a TVS called $`E` with coefficients in the normed field $`𝕜`
to the Lean environment:
```lean
variable (E 𝕜 : Type*) [NormedField 𝕜]
  [AddCommGroup E] [Module 𝕜 E]
  [TopologicalSpace E]
  [ContinuousAdd E] [ContinuousSMul 𝕜 E]
```
Since such a space is a topological group:
```lean
example : IsTopologicalAddGroup E :=
  { continuous_neg := by
      convert! continuous_const_smul (-1 : 𝕜) (T := E)
      ext; simp }
```
we could also assume {name}`IsTopologicalAddGroup` instead of {name}`ContinuousAdd` but
we usually make the superficially weaker assumption.

# Continuous Linear Maps

If $`F` is another TVS:
```lean
variable (F : Type*) [AddCommGroup F] [Module 𝕜 F]
  [TopologicalSpace F]
  [ContinuousAdd F] [ContinuousSMul 𝕜 F]
```
we can speak of the continuous linear maps between $`E` and $`F`. The relevant definition is
{name}`ContinuousLinearMap` and it has special notation as follows:
```lean
#check E →L[𝕜] F
```

```lean -show
end Temporary
```

# Locally convex spaces

```lean -show
section Temporary
```

Mathlib contains an extensive theory of locally convex spaces. The basic way to instantiate
a LCTVS is as follows:
```lean
variable (E 𝕜 : Type*) [NormedField 𝕜]
  [AddCommGroup E] [Module 𝕜 E]
  [TopologicalSpace E]
  [ContinuousAdd E] [ContinuousSMul 𝕜 E]
  [NormedSpace ℝ 𝕜] [Module ℝ E] [IsScalarTower ℝ 𝕜 E]
  [LocallyConvexSpace ℝ E]
```
For coefficients more general than $`ℝ` or $`ℂ` there is also {name}`PolynormableSpace`.
```lean -show
end Temporary
```

```lean -show
section Temporary
```
To say that $`E` is a TVS whose topology is generated by a family
of seminorms one writes:
```lean
variable {ι : Type*} (E 𝕜 : Type*) [NormedField 𝕜]
  [AddCommGroup E] [Module 𝕜 E]
  [TopologicalSpace E]
  [ContinuousAdd E] [ContinuousSMul 𝕜 E]
  {p : SeminormFamily 𝕜 E ι} (hp : WithSeminorms p)
```
and Mathlib knows that in this case the space is locally convex:
```lean
example
    [NormedSpace ℝ 𝕜] [Module ℝ E] [IsScalarTower ℝ 𝕜 E] :
    LocallyConvexSpace ℝ E := hp.toLocallyConvexSpace
```
```lean -show
end Temporary
```

# Banach and Hilbert spaces

To add a Banach space to the environment one writes:
```lean -show
section Temporary
```

```lean
variable (E 𝕜 : Type*) [NormedField 𝕜]
  [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  [CompleteSpace E]
```
Special notation for the norm is available for vectors in a Banach
space:
```lean
example (x y : E) : ‖x + y‖ ≤ ‖x‖ + ‖y‖ := norm_add_le x y
```
```lean -show
end Temporary

section Temporary
```
For a Hilbert space one writes:
```lean
variable (E 𝕜 : Type*) [RCLike 𝕜]
  [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
  [CompleteSpace E]
```
Special notation for the inner product is available for vectors in a Hilbert
space after opening the `InnerProductSpace` scope:
```lean
open scoped InnerProductSpace

example (x y : E) :
    ⟪x + y, x + y⟫_𝕜 + ⟪x - y, x - y⟫_𝕜 =
      2 * (⟪x, x⟫_𝕜 + ⟪y, y⟫_𝕜) :=
  parallelogram_law
```
```lean -show
end Temporary
```

# Notable results

The following are some notable results in Mathlib's theory library of topological
vector spaces:
- The *Open Mapping Theorem*: {name}`ContinuousLinearMap.isOpenMap`
- The *Hahn-Banach Theorem*: {name}`exists_extension_norm_eq`
- The *Lax-Milgram theorem*: {name}`IsCoercive.continuousLinearEquivOfBilin`
- The *Banach-Steinhaus theorem*: {name}`banach_steinhaus`
